### ISSUE TITLE
PHP Fatal error: Cannot redeclare class SLLH\ComposerVersionsCheck\VersionsCheckPlugin in Composer/Plugin/PluginManager.php(246)

### ISSUE THREAD

**Issue by limonte** [pyrech/composer-changelogs#21]
```
$ composer require --dev "pyrech/composer-changelogs"
Using version ^1.2 for pyrech/composer-changelogs
./composer.json has been updated
PHP Fatal error:  Cannot redeclare class SLLH\ComposerVersionsCheck\VersionsCheckPlugin in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(246) : eval()'d code on line 19

Fatal error: Cannot redeclare class SLLH\ComposerVersionsCheck\VersionsCheckPlugin in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(246) : eval()'d code on line 19
```

**Comment by pyrech** [comment]
Hi. Thanks for your issue. Regarding the error message, I don't think it's related to my package. The given namespace make me think that's probably an error with @Soullivaneuh's plugin.

Does this error only happens when installing my plugin or with any other package?

**Comment by Soullivaneuh** [comment]
@limonte please see:

* https://github.com/Soullivaneuh/composer-versions-check/issues/23
* https://github.com/composer/composer/pull/4482

Seems to be a composer issue.

BTW, if you run a `composer update` command after that, it will work. But I agree, it's quite annoying. :-)

**Comment by limonte** [comment]
@pyrech @Soullivaneuh thank you both for great plugins! Will workaround this issue with `composer update` for now :)
