### ISSUE TITLE
Undefined index: scheme

### ISSUE THREAD

**Issue by j0k3r** [pyrech/composer-changelogs#23]
While working on a local dependency, I defined it locally on my composer.json:

```
"repositories": [
    {
        "type":"vcs",
        "url":"/path/to/the/bundle"
    }
],
```

Everything went fine on composer up.
But I then switched back to _normal_ and removed my custom repositories directive. On the composer up, I got an error:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating my/awesome-bundle (dev-sf3.0 270ac26 => v1.4.7)
    Checking out ef6830dbbf62b22efd335db8f64bf0f51d4284a2

Writing lock file
Generating autoload files



  [ErrorException]
  Undefined index: scheme



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--] [<packages>]...
```

**Comment by pyrech** [comment]
Yes, the plugin certainly has a problem when handling local packages. I will need to investigate and find a way to handle these cases. Thanks for opening the issue.

**Comment by pyrech** [comment]
Sadly, even if I think I understand where the problem comes from and why it's happening, I could not reproduce it. Anyway, I just created #30 that should fix the problem once and for all.
