### ISSUE TITLE
Support for gitlab

### ISSUE THREAD

**Issue by Kitzberger** [pyrech/composer-changelogs#34]
In case that's possible I'd really like to see this plugin support self hosted gitlab instances as well.

Currently I do not have the time to do it myself but I thought to at least submit the idea as a start.

**Comment by pyrech** [comment]
Hi :)
Currently all the supported hosting services are detected within the source url of the package (mainly the domain of the service). So I don't see any way to detect that a package's url correspond to a self hosted gitlab instance. Is there a url structure that could uniquely detect a gitlab instance?

**Comment by Kitzberger** [comment]
Hm, I guess not since it's up to the person setting the whole thing how they wanna name the domain. The repository path isn't unique either.

    https://gitlab.company.org/project-name/repo-name

One could assume that everyone tends towards including gitlab in the domain name, but a better approach would be to make it configurable. Both ways would work in my case ;-)

**Comment by pyrech** [comment]
Hi @Kitzberger

Good news: I'm currently working on the feature :) But I don't have any instance of gitlab to play with. I see in Gitlab documentation that it supports releases but I cannot find anywhere what are the URLs of those release pages. For example, for Github, it's `github.com/[user name]/[repository name]/releases/tag/[name of the release]`.

Same question about compare URLs. Does Gitlab support them? If yes, can they be across forks like Github or Bitbucket support them? What is their structure? FYI, on Github, it's `github.com/[user name]/[repository name]/compare/[name of the version before update]...[name of the version after update]`

**Comment by Kitzberger** [comment]
That's great to hear ;-)

In our gitlab the URLs you're looking for are like this: https://gitlab.company.org/[project-name]/[repo-name]/tags/1.33.0

Comparing seems only to be working within one repository, not across forks: https://gitlab.company.org/[project-name]/[repo-name]/compare/master...feature%2Fdoes-something-different

Hope this info is useful to you. Let me know if I can be of any further assistance ;-)

**Comment by pyrech** [comment]
I just created #37 to implement this feature :wink:
