### ISSUE TITLE
Plugin can be register with a little hack

### ISSUE THREAD

**Issue by Soullivaneuh** [pyrech/composer-changelogs#35]
I saw this: https://github.com/pyrech/composer-changelogs/blob/be0fbc7d6f0b73dbad79d0ebf465671970b43f6f/tests/ChangelogsPluginTest.php#L97

You can achieve this using reflection: https://github.com/Soullivaneuh/composer-versions-check/blob/4810ab669723609a74bbf6c515d1aac2bd6562d3/tests/VersionsCheckPluginTest.php#L245-L251

What do you think?

Regards.

**Comment by pyrech** [comment]
Why not. I will give it a look later unless you provide a PR before :wink:
