### ISSUE TITLE
Lower PHP version requirement to 5.3

### ISSUE THREAD

**Issue by schlessera** [pyrech/composer-changelogs#43]
I would want to use your package in the WP-CLI project: https://github.com/wp-cli/wp-cli/pull/3881

However, we still support PHP 5.3, to adhere to Composer requirements (which is used for package management).

A quick look at the code revealed that short array syntax seems to be the only PHP 5.4-only feature that is being used.

It would be a quick change (without any backwards compatibility issues) to lower PHP requirement to 5.3+ instead of 5.4+.

**Comment by pyrech** [comment]
Answered in https://github.com/pyrech/composer-changelogs/pull/44#issuecomment-286422919
