### ISSUE TITLE
Long format changes description

### ISSUE THREAD

**Issue by erayaydin** [pyrech/composer-changelogs#60]
I think, there is an option for "long" format change show. For example, getting changes info from version tags within `git tag`.

For example
```
laravel/framework updated from 5.6 to 5.7
Changes for laravel/framework
- Change1
- Change2
- [Populate this list from git tag details from {fromVersion} to {toVersion}
```

Maybe, this can not be enhancement to project. Let me know :+1:

**Comment by pyrech** [comment]
Hello,

I'm not sure to understand how this could be possible because AFAIK there is no standard to describe changes in releases / tags. Moreover, changes can either be described in Github releases or in a CHANGELOG.md file or whatever else. Do you have more insight how this could work internally?

**Comment by erayaydin** [comment]
I think, we shouldn't enhancement this for only **git messages**. For example, `v1.3.0` to ``v1.3.6`

- Check version tags between `v1.3.0` to `v.1.3.6`
  - Is there any tag message for X
  - Append them to change log messages

```
git tag -ln X
```

We can't parse `CHANGELOG.md` file because of non-standard.
