### ISSUE TITLE
Drop old PHP versions

### ISSUE THREAD

**Issue by laurent35240** [pyrech/composer-changelogs#65]
Hi,

I think we can drop support of old PHP versions (< 7.1) since they are not supported by PHP ecosystem anymore.

It will resolve then failing builds in Travis also.

I can take care of it if you want

**Comment by pyrech** [comment]
Yep, I planned to do that as explained in https://github.com/pyrech/composer-changelogs/pull/63#issuecomment-540547504. But I you want to do it, be my guest :slightly_smiling_face: :+1:

**Comment by laurent35240** [comment]
I've done it here #66 
It unblocked Travis build and shown then some Code Style errors that I fixed too  😉
