### ISSUE TITLE
Usage with --dry-run

### ISSUE THREAD

**Issue by alessandro-podo** [pyrech/composer-changelogs#71]
is it possible to get the same output, when i use dry-run, that i can check it before i update?

**Comment by pyrech** [comment]
Hello @alessandro-podo. Thanks for opening this issue. I did not know the existence of the flag `--dry-run` on `composer update` command until now so I will need to give it a try soon and see how it behaves with the plugin.  :+1: 

In the mean time, if you or someone else want to make it work with this flag, PRs are welcome :wink:

**Comment by alessandro-podo** [comment]
Thanks for your fast answer. 

I try to read and understand how this could be done.

**Comment by pyrech** [comment]
Finally took some time to look at this issue. The sad news is that Composer seems to disable plugins & scripts when using the `--dry-run` flag :confused: https://github.com/composer/composer/blob/main/src/Composer/Installer.php#L254-L256

I don't know if this is something that could change on Composer side but for now, I don't think we can do anything to make use of this flag :confused: 

Do not hesitate to reopen this issue if something change in the future.
